/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Form;

import java.awt.Adjustable;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.AdjustmentEvent;
import java.awt.event.AdjustmentListener;
import java.time.LocalDateTime;

import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;
import net.miginfocom.swing.MigLayout;

public class Chat_body extends javax.swing.JPanel {

    /**
     * Creates new form Chat_body
     */
    public Chat_body() {
    initComponents();

    // DARK MODE
    setBackground(new java.awt.Color(30,30,46));
    setOpaque(true);

    body.setBackground(new java.awt.Color(49,50,68));
    body.setOpaque(true);

    scroll.setBackground(new java.awt.Color(49,50,68));
    scroll.getViewport().setBackground(new java.awt.Color(49,50,68));

    scroll.setBorder(null);

    init();

    scroll.getViewport().setViewPosition(
        new Point(0, scroll.getVerticalScrollBar().getMaximum())
    );
}

    public void init() {
        body.setLayout(new MigLayout("fillx", "", "5[]5"));
        scroll.setVerticalScrollBar(new JScrollBar());
        scroll.getVerticalScrollBar().setBackground(new Color(24,24,37));
    }

    public void addItemLeft(String text) {
        Chat_left item = new Chat_left();

        // kalau string chat mengandung tanda titik dua ": "
        if (text.contains(": ")) {
            String[] parts = text.split(": ", 2);
            String sender = parts[0].toUpperCase();
            String message = parts[1];

            // pisahin dengan baris baru (\n)
            item.setText(sender + "\n" + message);
        } else {
            item.setText(text);
        }

        body.add(item, "wrap, w ::60%");
        body.repaint();
        body.revalidate();
        scrollToBottom(scroll);
    }

    public void addItemRight(String text) {
        Chat_right item = new Chat_right();
        
        item.setText(text);

        body.add(item, "wrap, al right, w ::60%");
        body.repaint();
        body.revalidate();
        scrollToBottom(scroll);
    }

    private void scrollToBottom(JScrollPane scrollPane) {
        JScrollBar verticalBar = scrollPane.getVerticalScrollBar();
        AdjustmentListener downScroller = new AdjustmentListener() {
            @Override
            public void adjustmentValueChanged(AdjustmentEvent e) {
                Adjustable adjustable = e.getAdjustable();
                adjustable.setValue(adjustable.getMaximum());
                verticalBar.removeAdjustmentListener(this);
            }
        };
        verticalBar.addAdjustmentListener(downScroller);
    }
    
    public void removeAllItems() {
        body.removeAll(); // Remove all components from the 'body' JPanel
        body.revalidate(); // Re-calculate layout
        body.repaint();   // Re-draw the panel
    }

    public void addImageLeft(String sender, byte[] imageData, LocalDateTime timestamp) {
        Chat_image_left item = new Chat_image_left(sender,imageData,timestamp);
        body.add(
                item,
                "wrap, w ::60%"
        );
        body.repaint();
        body.revalidate();
        scrollToBottom(scroll);
    }

    public void addImageRight(byte[] imageData,LocalDateTime timestamp) {
        Chat_image_right item = new Chat_image_right(imageData, timestamp);
        body.add(
                item,
                "wrap, al right, w ::60%"
        );
        body.repaint();
        body.revalidate();
        scrollToBottom(scroll);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        body = new javax.swing.JPanel();

        scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scroll.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        body.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        scroll.setViewportView(body);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
