/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Form;

import ServerClient.Message;

public class Group_bar extends javax.swing.JPanel {

    private String clientName;
    private String thisRoom;
    private Chat_window chatWindowRef;

    public Group_bar(String name, String clientName, String thisRoom, Chat_window chatWindowRef) {
        initComponents();
        label.setText(name);
        this.clientName = clientName;
        this.thisRoom = thisRoom;
        this.chatWindowRef = chatWindowRef;
        initControls();

        setBackground(new java.awt.Color(24, 24, 37));
        setOpaque(true);

        label.setForeground(java.awt.Color.WHITE);

        infoButton.setBackground(new java.awt.Color(88, 91, 112));
        infoButton.setForeground(java.awt.Color.WHITE);

        infoButton.setBorderPainted(false);
        infoButton.setFocusPainted(false);
        infoButton.setContentAreaFilled(false);
        infoButton.setOpaque(true);

        infoButton.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));

        label.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));

        imageAvatar2.setImage(new javax.swing.ImageIcon(
                getClass().getResource("/Icon/Kapibara.png")
        ));
    }

    private void initControls() {
        infoButton.addActionListener(e -> showRoomInfo());
    }

    private void showRoomInfo() {
        chatWindowRef.sendMessage(new Message(clientName, "Requesting info for " + thisRoom + " from Group List",
                Message.MessageType.ROOM_INFO_REQUEST, thisRoom));
        System.out.println(clientName + " requesting info for room: " + thisRoom);
        //chatWindowRef.sendMessage(new Message(clientName, "Requesting users from group bar", Message.MessageType.USERS_IN_ROOM_REQUEST, thisRoom));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        imageAvatar2 = new multiple_chat_room.ImageAvatar();
        infoButton = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setFocusable(false);
        setPreferredSize(new java.awt.Dimension(350, 60));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);

        label.setText("Name");

        imageAvatar2.setBorderSize(0);

        infoButton.setText("Info");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageAvatar2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoButton)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageAvatar2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(infoButton)
                            .addComponent(label))))
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private multiple_chat_room.ImageAvatar imageAvatar2;
    private javax.swing.JButton infoButton;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
